spring:
  application:
    name: atlas-bank
  datasource:
    url: jdbc:postgresql://localhost:5432/atlasbankdb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/atlas-bank

keycloak:
  url: http://localhost:8080
  realm: atlas-bank
  client-id: atlas-bank-api
  client-secret: DMSkXwC0p0Xo5eBwnzgUTqqQR0YXNfNZ

server:
  port: 8081
